### ISSUE TITLE
Error in executing Java code from API request ☕

### ISSUE THREAD

**Issue by kashwa** [kashwa/backendIntegration#1]
I faced an error in executing java code from php request to the script on server 

```
java.lang.UnsupportedClassVersionError: test_hello_world :
 Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(Unknown Source)
       .........................................
```

**Comment by kashwa** [comment]
### After looking into resources 🔗

https://www.journaldunet.fr/web-tech/developpement/1203047-unsupported-major-minor-version-52-0-comment-eviter-cette-erreur/

I was able to fix the first **Issue** which was about _Matching_ the version of the **JRE** with the **JDK**.

```
The old JDK was 13
and JRE was 8
```

I Fixed it so it would be
```
JDK 8
and JRE 8
```

![image](https://user-images.githubusercontent.com/20141910/83417596-9a223d80-a422-11ea-9cf3-2c27cd170793.png)

**Comment by kashwa** [comment]
## Another bug in Executing Compiled Class 🐜

I had this error when i try to execute the compiled class

```Error: Could not find or load main class```

After looking at these resources 🔗

(1) https://javarevisited.blogspot.com/2015/04/error-could-not-find-or-load-main-class-helloworld-java.html

(2) https://stackoverflow.com/questions/18093928/what-does-could-not-find-or-load-main-class-mean

I was able to execute the java code successfully from PHP api
